import {songById} from './songs.js';
import {RoomError,assertRoom} from './room-state.js';
export function freshGame(song='maija',revision=1){return {song,revision,approved:{pitch:false,duration:false},phase:'select',startAt:0,progress:{pitch:0,duration:0},finished:{pitch:0,duration:0},mistakes:{pitch:0,duration:0},wrong:{pitch:-2,duration:0},wrongAt:{pitch:0,duration:0}};}
function member(room,uid,now){assertRoom(room,now);if(!room.players[uid])throw new RoomError('member','Huone ei ole enää avoinna.');return room.players[uid].role;}
const changed=(room,game,now)=>({...room,game,updatedAt:now});
export function chooseSong(room,uid,song,revision,now){member(room,uid,now);if(!songById(song))throw new RoomError('song','Kappaletta ei löytynyt.');if(room.game.phase!=='select'||room.game.revision!==revision)throw new RoomError('stale','Valinta muuttui.');if(song===room.game.song)return room;return changed(room,freshGame(song,revision+1),now);}
export function approveSong(room,uid,revision,now){const role=member(room,uid,now);const g=room.game;if(Object.keys(room.players).length!==2||g.phase!=='select'||g.revision!==revision)throw new RoomError('stale','Tarkista uusi valinta ja hyväksy se uudelleen.');if(g.approved[role])return room;const approved={...g.approved,[role]:true};return changed(room,{...g,approved,phase:approved.pitch&&approved.duration?'play':'select',startAt:approved.pitch&&approved.duration?now+4000:0},now);}
export function answerGame(room,uid,value,revision,index,now){const role=member(room,uid,now),g=room.game;if(g.phase!=='play'||g.revision!==revision||g.progress[role]!==index||now<g.startAt)throw new RoomError('stale','Odota seuraavaa nuottia.');const song=songById(g.song),n=song.notes[index];if(!n) return room;const correct=value===(role==='pitch'?n.pitch:n.duration*(n.rest?-1:1));if(!correct)return changed(room,{...g,mistakes:{...g.mistakes,[role]:g.mistakes[role]+1},wrong:{...g.wrong,[role]:value},wrongAt:{...g.wrongAt,[role]:now}},now);const progress={...g.progress,[role]:index+1},finished={...g.finished,[role]:index+1===song.notes.length?now:0};return changed(room,{...g,progress,finished,wrong:{...g.wrong,[role]:role==='pitch'?-2:0},wrongAt:{...g.wrongAt,[role]:0},phase:finished.pitch&&finished.duration?'done':'play'},now);}
export function restartGame(room,uid,revision,now){member(room,uid,now);if(room.game.phase!=='done'||room.game.revision!==revision)throw new RoomError('stale','Kierros on vielä kesken.');return changed(room,freshGame(room.game.song,revision+1),now);}
export const elapsed=(g,role,now)=>g.startAt?Math.max(0,(g.finished[role]||now)-g.startAt):0;
