// YIN difference function. One attack per articulated note; a held note never
// consumes repeated notes. Audio stays on this device.
export function detectPitch(buffer,sampleRate){let energy=0;for(const v of buffer)energy+=v*v;if(Math.sqrt(energy/buffer.length)<0.009)return null;const max=Math.min(Math.floor(sampleRate/220),buffer.length/2),min=Math.floor(sampleRate/1800),d=new Float32Array(max+1);let sum=0;for(let tau=1;tau<=max;tau++){let diff=0;for(let j=0;j<buffer.length-max;j++){const v=buffer[j]-buffer[j+tau];diff+=v*v;}sum+=diff;d[tau]=sum?diff*tau/sum:1;}for(let tau=min;tau<max-1;tau++){if(d[tau]<0.16){while(tau+1<max&&d[tau+1]<d[tau])tau++;const a=d[tau-1],b=d[tau],c=d[tau+1],den=2*(2*b-a-c),ref=tau+(den?(c-a)/den:0);return sampleRate/ref;}}return null;}
export class FluteInput{
 constructor(onNote,onLevel){this.onNote=onNote;this.onLevel=onLevel;this.active=false;this.token=0;}
 async start(){if(this.active){await this.context.resume();return;}if(!navigator.mediaDevices?.getUserMedia)throw new Error('Mikrofoni tarvitsee HTTPS-osoitteen.');const token=++this.token;this.context=new (window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});await this.context.resume();let stream;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});}catch(e){await this.context.close();throw new Error(e.name==='NotAllowedError'?'Salli mikrofonin käyttö ja yritä uudelleen.':'Mikrofonia ei saatu avattua.');}if(token!==this.token){stream.getTracks().forEach(t=>t.stop());return;}this.stream=stream;this.source=this.context.createMediaStreamSource(stream);this.analyser=this.context.createAnalyser();this.analyser.fftSize=2048;this.source.connect(this.analyser);this.buffer=new Float32Array(2048);this.active=true;this.reset();this.tick();}
 reset(){this.last=null;this.stable=0;this.latched=null;this.silence=0;}
 tick(){if(!this.active)return;this.analyser.getFloatTimeDomainData(this.buffer);const f=detectPitch(this.buffer,this.context.sampleRate),now=performance.now();let midi=null;if(f){const raw=69+12*Math.log2(f/440),rounded=Math.round(raw);if(Math.abs(raw-rounded)<=0.49)midi=rounded;}
 this.onLevel?.(midi);if(midi===null){if(!this.silence)this.silence=now;if(now-this.silence>55)this.latched=null;this.last=null;this.stable=0;}else{this.silence=0;if(midi!==this.last){this.last=midi;this.stable=now;}if(now-this.stable>=55&&midi!==this.latched){this.latched=midi;this.onNote(midi);}}this.frame=requestAnimationFrame(()=>this.tick());}
 stop(){++this.token;this.active=false;cancelAnimationFrame(this.frame);this.stream?.getTracks().forEach(t=>t.stop());this.source?.disconnect();this.context?.close();}
}
