/* Nuottikompassi Microphone Engine 1.0
 * Package version: 1.0
 * Source engine: Nuottikompassi 4.0.2 Base
 * Recognition, filtering, calibration and reference-tone logic are unchanged.
 */
(function(global){
'use strict';
const DEFAULTS=Object.freeze({inputGain:4,sensitivity:60,confidence:72,reactionSpeed:5,ambitus:5,hysteresisCents:12,meterSensitivity:1,tuningA4Hz:440,referenceEnabled:false,liveReferenceEnabled:true});
const AUDIO=Object.freeze({fftSize:2048,minFrequency:235,maxFrequency:2200,analysisIntervalMs:32,silenceUiDelayMs:420,referenceDelayMs:700,referenceDurationMs:2000,referenceReleaseMs:120,referenceGuardMs:300,liveReferenceReleaseMs:80,liveReferenceHoldMs:180});
const METER_PROFILES=Object.freeze({1:{deadZoneCents:4,historySize:9,awayAlpha:.16,returnAlpha:.08,maxAwayStep:4,maxReturnStep:2},2:{deadZoneCents:3,historySize:7,awayAlpha:.24,returnAlpha:.12,maxAwayStep:6,maxReturnStep:3},3:{deadZoneCents:2,historySize:5,awayAlpha:.34,returnAlpha:.16,maxAwayStep:8,maxReturnStep:4},4:{deadZoneCents:1,historySize:3,awayAlpha:.48,returnAlpha:.26,maxAwayStep:12,maxReturnStep:7},5:{deadZoneCents:0,historySize:1,awayAlpha:.75,returnAlpha:.5,maxAwayStep:20,maxReturnStep:14}});
const SPELLINGS=Object.freeze([
 {letter:'C',display:'C',accidental:'none'}, {letter:'C',display:'C♯',accidental:'sharp'},
 {letter:'D',display:'D',accidental:'none'}, {letter:'E',display:'E♭',accidental:'flat'},
 {letter:'E',display:'E',accidental:'none'}, {letter:'F',display:'F',accidental:'none'},
 {letter:'F',display:'F♯',accidental:'sharp'}, {letter:'G',display:'G',accidental:'none'},
 {letter:'G',display:'G♯',accidental:'sharp'}, {letter:'A',display:'A',accidental:'none'},
 {letter:'B',display:'B♭',accidental:'flat'}, {letter:'B',display:'B',accidental:'none'}
]);
const LETTER_INDEX=Object.freeze({C:0,D:1,E:2,F:3,G:4,A:5,B:6});
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
const median=values=>{if(!values.length)return 0;const a=[...values].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;};
function frequencyToMidi(frequency,a4=440){return 69+12*Math.log2(frequency/a4);}
function midiToFrequency(midi,a4=440){return a4*Math.pow(2,(midi-69)/12);}
function noteInfo(midi){const rounded=Math.round(midi),pc=((rounded%12)+12)%12,base=SPELLINGS[pc],octave=Math.floor(rounded/12)-1;const diatonic=octave*7+LETTER_INDEX[base.letter];return {...base,midi:rounded,pitchClass:pc,octave,step:diatonic-(4*7+LETTER_INDEX.B),label:`${base.display}${octave}`};}
function diatonicDistance(a,b){return Math.abs(noteInfo(a).step-noteInfo(b).step);}
function rmsDb(buffer){let sum=0;for(let i=0;i<buffer.length;i++)sum+=buffer[i]*buffer[i];return 20*Math.log10(Math.max(Math.sqrt(sum/buffer.length),1e-8));}
function createYinDetector(bufferLength,sampleRate){
 const minTau=Math.max(2,Math.floor(sampleRate/AUDIO.maxFrequency));
 const maxTau=Math.min(Math.floor(sampleRate/AUDIO.minFrequency),Math.floor(bufferLength/2)-1);
 const analysisLength=bufferLength-maxTau,centered=new Float32Array(bufferLength),difference=new Float32Array(maxTau+1),cumulative=new Float32Array(maxTau+1);
 return function detect(input,minimumConfidence){
  let mean=0;for(let i=0;i<bufferLength;i++)mean+=input[i];mean/=bufferLength;for(let i=0;i<bufferLength;i++)centered[i]=input[i]-mean;
  difference.fill(0);for(let tau=1;tau<=maxTau;tau++){let sum=0;for(let i=0;i<analysisLength;i++){const delta=centered[i]-centered[i+tau];sum+=delta*delta;}difference[tau]=sum;}
  cumulative[0]=1;let running=0;for(let tau=1;tau<=maxTau;tau++){running+=difference[tau];cumulative[tau]=running>0?difference[tau]*tau/running:1;}
  let tauEstimate=-1;for(let tau=minTau;tau<=maxTau;tau++){if(cumulative[tau]<.18){while(tau+1<=maxTau&&cumulative[tau+1]<cumulative[tau])tau++;tauEstimate=tau;break;}}
  if(tauEstimate<0){let best=minTau;for(let tau=minTau+1;tau<=maxTau;tau++)if(cumulative[tau]<cumulative[best])best=tau;tauEstimate=best;}
  const confidence=clamp(1-cumulative[tauEstimate],0,1);if(confidence<minimumConfidence)return null;
  const lt=Math.max(minTau,tauEstimate-1),rt=Math.min(maxTau,tauEstimate+1),left=cumulative[lt],middle=cumulative[tauEstimate],right=cumulative[rt],den=2*(2*middle-right-left);
  const refined=Math.abs(den)>1e-9?tauEstimate+(right-left)/den:tauEstimate,frequency=sampleRate/refined;
  if(!Number.isFinite(frequency)||frequency<AUDIO.minFrequency||frequency>AUDIO.maxFrequency)return null;
  return {frequency,confidence,tau:refined};
 };
}
class MicrophoneEngine{
 constructor(settings={},onUpdate=()=>{}){this.settings={...DEFAULTS,...settings};this.onUpdate=onUpdate;this._resetRuntime();}
 _resetRuntime(){this.stream=null;this.audioContext=null;this.source=null;this.inputGainNode=null;this.analyser=null;this.timeData=null;this.yinDetector=null;this.running=false;this.animationId=0;this.token=0;this.lastAnalysisAt=0;this.lastValidAt=0;this.silenceStartedAt=0;this.activeMidi=null;this.pendingMidi=null;this.pendingFrames=0;this.pendingRequired=0;this.filteredCents=null;this.meterFilteredCents=null;this.meterHistory=[];this.lastOutput={status:'idle',active:false};this.referenceArmed=false;this.referenceMidi=null;this.referencePlaying=false;this.referencePlayedSinceUser=false;this.referenceIgnoreUntil=0;this.referenceNodes=null;this.referenceCleanupTimer=0;this.liveReferencePlaying=false;this.liveReferenceMidi=null;this.liveReferenceNodes=null;this.liveReferenceLastSeenAt=0;this.liveReferenceCleanupTimer=0;}
 updateSettings(settings={}){Object.assign(this.settings,settings);if(this.inputGainNode&&this.audioContext)this.inputGainNode.gain.setTargetAtTime(Number(this.settings.inputGain),this.audioContext.currentTime,.015);}
 _emit(patch){this.lastOutput={...this.lastOutput,...patch,running:this.running};this.onUpdate({...this.lastOutput});}
 _candidateForFrequency(frequency,useHysteresis=true){const mf=frequencyToMidi(frequency,Number(this.settings.tuningA4Hz)),nearest=Math.round(mf);let midi=nearest,distance=Math.abs(mf-nearest)*100;if(useHysteresis&&this.activeMidi!==null&&midi!==this.activeMidi){const activeDistance=Math.abs(mf-this.activeMidi)*100;if(activeDistance-distance<Number(this.settings.hysteresisCents))midi=this.activeMidi;}return {midi,cents:(mf-midi)*100,frequency};}
 _resolvePitch(result){const primary=this._candidateForFrequency(result.frequency,true),alts=[];for(const factor of [.5,2]){const f=result.frequency*factor;if(f>=AUDIO.minFrequency&&f<=AUDIO.maxFrequency)alts.push(this._candidateForFrequency(f,false));}const activeAlternative=this.activeMidi===null?null:alts.find(x=>x.midi===this.activeMidi);const octaveAmbiguous=Boolean(activeAlternative&&Math.abs(primary.midi-this.activeMidi)>=10&&Math.abs(primary.midi-this.activeMidi)<=14);return {...primary,confidence:result.confidence,octaveAmbiguous,octaveAlternatives:alts};}
 _reactionConfirmations(){return ({1:4,2:3,3:2,4:2,5:1})[Number(this.settings.reactionSpeed)]||1;}
 _required(candidate){const base=this._reactionConfirmations();if(this.activeMidi===null)return base;const semis=Math.abs(candidate.midi-this.activeMidi);if(semis===1)return Math.max(base,3);if(diatonicDistance(this.activeMidi,candidate.midi)<=Number(this.settings.ambitus)-1)return base;let required=Math.max(base,3);if(candidate.midi<this.activeMidi)required=Math.max(required,4);if(candidate.octaveAmbiguous)required=Math.max(required,5);return required;}
 _resetPending(){this.pendingMidi=null;this.pendingFrames=0;this.pendingRequired=0;}
 _meter(raw){const p=METER_PROFILES[Number(this.settings.meterSensitivity)]||METER_PROFILES[1];this.meterHistory.push(raw);if(this.meterHistory.length>p.historySize)this.meterHistory.shift();let target=median(this.meterHistory);target=Math.abs(target)<=p.deadZoneCents?0:clamp(target,-50,50);if(this.meterFilteredCents===null)this.meterFilteredCents=target;else{const current=this.meterFilteredCents,directionChanged=Math.sign(target)!==Math.sign(current)&&Math.abs(target)>p.deadZoneCents,movingAway=directionChanged||Math.abs(target)>Math.abs(current)+.5,alpha=movingAway?p.awayAlpha:p.returnAlpha,maxStep=movingAway?p.maxAwayStep:p.maxReturnStep,desired=(target-current)*alpha;this.meterFilteredCents=current+clamp(desired,-maxStep,maxStep);if(target===0&&Math.abs(this.meterFilteredCents)<.6)this.meterFilteredCents=0;}return clamp(this.meterFilteredCents,-50,50);}
 _acceptedOutput(candidate,db){const info=noteInfo(candidate.midi);this.filteredCents=this.filteredCents===null?candidate.cents:this.filteredCents*.55+candidate.cents*.45;const meterCents=this._meter(candidate.cents);return {status:'signal',active:true,frequency:candidate.frequency,midi:candidate.midi,midiFloat:frequencyToMidi(candidate.frequency,Number(this.settings.tuningA4Hz)),cents:this.filteredCents,rawCents:candidate.cents,meterCents,confidence:candidate.confidence*100,db,step:info.step,accidental:info.accidental,noteName:info.label,display:info.display,octave:info.octave,pitchClass:info.pitchClass};}
 _processCandidate(candidate,db){if(this.activeMidi===candidate.midi){this._resetPending();this._emit(this._acceptedOutput(candidate,db));return;}const required=this._required(candidate);if(this.pendingMidi===candidate.midi)this.pendingFrames++;else{this.pendingMidi=candidate.midi;this.pendingFrames=1;this.pendingRequired=required;}if(this.pendingFrames>=this.pendingRequired){this.activeMidi=candidate.midi;this._resetPending();this._emit(this._acceptedOutput(candidate,db));}else this._emit({status:candidate.octaveAmbiguous?'confirming-octave':'confirming-note',active:false,db,frequency:candidate.frequency,confidence:candidate.confidence*100});}
 async start(){if(this.running)return;this._emit({status:'opening',error:null});if(!navigator.mediaDevices?.getUserMedia){this._emit({status:'error',error:'Selain ei tarjoa mikrofonikäyttöä tässä osoitteessa.'});return;}let context=null,stream=null;try{const AC=window.AudioContext||window.webkitAudioContext;context=new AC({latencyHint:'interactive'});this.audioContext=context;await context.resume();stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});const source=context.createMediaStreamSource(stream),gain=context.createGain(),analyser=context.createAnalyser();gain.gain.setValueAtTime(Number(this.settings.inputGain),context.currentTime);analyser.fftSize=AUDIO.fftSize;analyser.smoothingTimeConstant=0;source.connect(gain);gain.connect(analyser);this.stream=stream;this.source=source;this.inputGainNode=gain;this.analyser=analyser;this.timeData=new Float32Array(analyser.fftSize);this.yinDetector=createYinDetector(analyser.fftSize,context.sampleRate);this.running=true;this.lastAnalysisAt=0;const token=++this.token;this._emit({status:'waiting',active:false,error:null});this.animationId=requestAnimationFrame(t=>this._loop(t,token));}catch(error){console.error(error);if(stream)for(const track of stream.getTracks())track.stop();if(context&&context.state!=='closed')try{await context.close();}catch(_){}this.audioContext=null;this.stream=null;this._emit({status:'error',error:'Mikrofonia ei saatu käyttöön. Tarkista mikrofonilupa ja valittu äänitulo.'});}}
 async stop(){this.running=false;this.token++;cancelAnimationFrame(this.animationId);this._stopReferenceTone();this._clearReferenceNodes();this._stopLiveReferenceTone(true);this._clearLiveReferenceNodes();if(this.stream)for(const track of this.stream.getTracks())track.stop();if(this.audioContext)try{await this.audioContext.close();}catch(_){}this.stream=null;this.audioContext=null;this.source=null;this.inputGainNode=null;this.analyser=null;this.timeData=null;this.yinDetector=null;this._resetPending();this._emit({status:'idle',active:false,db:-160,error:null});}
 _loop(now,token){if(!this.running||token!==this.token)return;this.animationId=requestAnimationFrame(t=>this._loop(t,token));if(now-this.lastAnalysisAt<AUDIO.analysisIntervalMs)return;this.lastAnalysisAt=now;if(this.referencePlaying||now<this.referenceIgnoreUntil){this._stopLiveReferenceTone(true);return;}this.analyser.getFloatTimeDomainData(this.timeData);const db=rmsDb(this.timeData),voiced=db>-Number(this.settings.sensitivity);if(!voiced){this._resetPending();this._maybeStopLiveReference(now);if(!this.silenceStartedAt)this.silenceStartedAt=now;this._maybePlayReference(now);this._emit({status:this.activeMidi===null?'waiting':'holding',active:false,db});return;}this.silenceStartedAt=0;const pitch=this.yinDetector(this.timeData,Number(this.settings.confidence)/100);if(!pitch){this._resetPending();this._maybeStopLiveReference(now);this._emit({status:'unstable',active:false,db});return;}const candidate=this._resolvePitch(pitch);this.lastValidAt=now;this._ensureLiveReferenceTone(candidate.midi,now);this._processCandidate(candidate,db);this._armReference();}
 _clearLiveReferenceNodes(){if(this.liveReferenceCleanupTimer){clearTimeout(this.liveReferenceCleanupTimer);this.liveReferenceCleanupTimer=0;}if(!this.liveReferenceNodes)return;for(const item of this.liveReferenceNodes.items){try{item.oscillator.stop();}catch(_){}try{item.oscillator.disconnect();}catch(_){}}try{this.liveReferenceNodes.master.disconnect();}catch(_){}this.liveReferenceNodes=null;this.liveReferencePlaying=false;this.liveReferenceMidi=null;}
 _stopLiveReferenceTone(immediate=false){const nodes=this.liveReferenceNodes,context=this.audioContext;if(!nodes||!context){this._clearLiveReferenceNodes();return;}if(this.liveReferenceCleanupTimer){clearTimeout(this.liveReferenceCleanupTimer);this.liveReferenceCleanupTimer=0;}const now=context.currentTime,release=immediate?.01:AUDIO.liveReferenceReleaseMs/1000;try{nodes.master.gain.cancelScheduledValues(now);nodes.master.gain.setValueAtTime(Math.max(nodes.master.gain.value,.0001),now);nodes.master.gain.linearRampToValueAtTime(0,now+release);}catch(_){}this.liveReferencePlaying=false;this.liveReferenceMidi=null;this.liveReferenceCleanupTimer=setTimeout(()=>this._clearLiveReferenceNodes(),Math.ceil(release*1000)+40);}
 _ensureLiveReferenceTone(midi,nowMs){if(!this.settings.liveReferenceEnabled||this.referencePlaying||!this.audioContext||!Number.isFinite(midi))return;this.liveReferenceLastSeenAt=nowMs;const context=this.audioContext,frequency=midiToFrequency(midi,Number(this.settings.tuningA4Hz));if(this.liveReferenceNodes){const now=context.currentTime;if(!this.liveReferencePlaying){if(this.liveReferenceCleanupTimer){clearTimeout(this.liveReferenceCleanupTimer);this.liveReferenceCleanupTimer=0;}try{this.liveReferenceNodes.master.gain.cancelScheduledValues(now);this.liveReferenceNodes.master.gain.setValueAtTime(Math.max(this.liveReferenceNodes.master.gain.value,.0001),now);this.liveReferenceNodes.master.gain.linearRampToValueAtTime(.075,now+.035);}catch(_){}this.liveReferencePlaying=true;}if(this.liveReferenceMidi!==midi){for(const item of this.liveReferenceNodes.items){const target=frequency*item.multiple;try{item.oscillator.frequency.cancelScheduledValues(now);item.oscillator.frequency.setValueAtTime(Math.max(item.oscillator.frequency.value,1),now);item.oscillator.frequency.exponentialRampToValueAtTime(Math.max(target,1),now+.045);}catch(_){item.oscillator.frequency.setValueAtTime(target,now);}}this.liveReferenceMidi=midi;}return;}const startTone=()=>{if(!this.running||!this.settings.liveReferenceEnabled||this.referencePlaying||this.liveReferenceNodes)return;const start=context.currentTime+.01,master=context.createGain();master.gain.setValueAtTime(0,start);master.gain.linearRampToValueAtTime(.075,start+.035);master.connect(context.destination);const items=[{multiple:1,level:1},{multiple:2,level:.14},{multiple:3,level:.04}].map(({multiple,level})=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(frequency*multiple,start);gain.gain.setValueAtTime(level,start);oscillator.connect(gain).connect(master);oscillator.start(start);return{oscillator,gain,multiple};});this.liveReferenceNodes={items,master};this.liveReferencePlaying=true;this.liveReferenceMidi=midi;};context.state==='suspended'?context.resume().then(startTone).catch(()=>{}):startTone();}
 _maybeStopLiveReference(now){if(this.liveReferenceNodes&&now-this.liveReferenceLastSeenAt>=AUDIO.liveReferenceHoldMs)this._stopLiveReferenceTone();}
 _clearReferenceNodes(){if(this.referenceCleanupTimer){clearTimeout(this.referenceCleanupTimer);this.referenceCleanupTimer=0;}if(!this.referenceNodes)return;for(const oscillator of this.referenceNodes.oscillators){try{oscillator.stop();}catch(_){}try{oscillator.disconnect();}catch(_){}}try{this.referenceNodes.master.disconnect();}catch(_){}this.referenceNodes=null;}
 _stopReferenceTone(){if(!this.referencePlaying&&!this.referenceNodes)return;const context=this.audioContext,nodes=this.referenceNodes;if(context&&nodes){const now=context.currentTime;try{nodes.master.gain.cancelScheduledValues(now);nodes.master.gain.setValueAtTime(Math.max(nodes.master.gain.value,.0001),now);nodes.master.gain.linearRampToValueAtTime(0,now+.04);}catch(_){}}this.referencePlaying=false;this.referenceIgnoreUntil=performance.now()+AUDIO.referenceGuardMs;setTimeout(()=>this._clearReferenceNodes(),70);}
 _playReferenceTone(midi){if(!this.settings.referenceEnabled||this.referencePlaying||!this.audioContext||!Number.isFinite(midi))return;this._stopLiveReferenceTone(true);const context=this.audioContext,startTone=()=>{if(!this.running||!this.settings.referenceEnabled||this.referencePlaying)return;this._clearReferenceNodes();const frequency=midiToFrequency(midi,Number(this.settings.tuningA4Hz)),start=context.currentTime+.02,releaseStart=start+AUDIO.referenceDurationMs/1000,stopAt=releaseStart+AUDIO.referenceReleaseMs/1000,master=context.createGain();master.gain.setValueAtTime(0,start);master.gain.linearRampToValueAtTime(.13,start+.06);master.gain.setValueAtTime(.13,releaseStart);master.gain.linearRampToValueAtTime(0,stopAt);master.connect(context.destination);const oscillators=[{multiple:1,level:1},{multiple:2,level:.18},{multiple:3,level:.06}].map(({multiple,level})=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(frequency*multiple,start);gain.gain.setValueAtTime(level,start);oscillator.connect(gain).connect(master);oscillator.start(start);oscillator.stop(stopAt+.03);return oscillator;});this.referenceNodes={oscillators,master};this.referencePlaying=true;this.referenceArmed=false;this.referencePlayedSinceUser=true;this.silenceStartedAt=0;this._emit({status:'reference',active:false});this.referenceCleanupTimer=setTimeout(()=>{this._clearReferenceNodes();this.referencePlaying=false;this.referenceIgnoreUntil=performance.now()+AUDIO.referenceGuardMs;},AUDIO.referenceDurationMs+AUDIO.referenceReleaseMs+120);};context.state==='suspended'?context.resume().then(startTone).catch(()=>{}):startTone();}
 _armReference(){if(this.settings.referenceEnabled&&this.activeMidi!==null){this.referenceMidi=this.activeMidi;this.referenceArmed=true;this.referencePlayedSinceUser=false;}}
 _maybePlayReference(now){if(this.settings.referenceEnabled&&this.referenceArmed&&!this.referencePlaying&&this.referenceMidi!==null&&this.silenceStartedAt&&now-this.silenceStartedAt>=AUDIO.referenceDelayMs)this._playReferenceTone(this.referenceMidi);}
 analyzeSamples(samples,sampleRate=48000){const detector=createYinDetector(samples.length,sampleRate),result=detector(samples,Number(this.settings.confidence)/100);if(!result)return null;return this._resolvePitch(result);}
}
global.NuottikompassiMicrophoneEngine=Object.freeze({VERSION:'1.0',PACKAGE_VERSION:'1.0',SOURCE_VERSION:'4.0.2',BUILD:'archive-1',DEFAULTS,AUDIO,METER_PROFILES,MicrophoneEngine,createYinDetector,frequencyToMidi,midiToFrequency,noteInfo,rmsDb});
})(window);