const cfg={apiKey:'AIzaSyCHSTODIddId7jxP41X315gx4s-pfQ1l44',authDomain:'savelkoju.firebaseapp.com',projectId:'savelkoju',storageBucket:'savelkoju.firebasestorage.app',messagingSenderId:'628559357855',appId:'1:628559357855:web:af1896e724516187abbfaa'};
firebase.initializeApp(cfg);const auth=firebase.auth(),db=firebase.firestore();let lastPlayerDoc=null,currentEdit=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function fmt(v){const d=v?.toDate?v.toDate():new Date(Number(v)||0);return isNaN(d)?'–':d.toLocaleString('fi-FI')}
async function isAdmin(u){return (await db.collection('admins').doc(u.uid).get()).exists}
auth.onAuthStateChanged(async u=>{if(u&&await isAdmin(u)){ $('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#userLabel').textContent=u.email;await Promise.all([loadOverview(),loadPlayers(true),loadLevels(),loadRewards()]);}else{$('#app').classList.add('hidden');$('#login').classList.remove('hidden');if(u)await auth.signOut();}});
$('#loginBtn').onclick=async()=>{try{$('#loginStatus').textContent='';await auth.signInWithEmailAndPassword($('#email').value.trim(),$('#password').value)}catch(e){$('#loginStatus').textContent='Kirjautuminen epäonnistui: '+e.message}};$('#logoutBtn').onclick=()=>auth.signOut();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$('#'+b.dataset.tab).classList.remove('hidden')});
async function loadOverview(){const ps=await db.collection('publicPlayers').get();let rewards=0;ps.forEach(d=>rewards+=Number(d.data().cabinetCount)||0);$('#mPlayers').textContent=ps.size;$('#mRewards').textContent=rewards;const ss=await db.collectionGroup('sessions').orderBy('createdAt','desc').limit(100).get();$('#mSessions').textContent=ss.size;let perfect=0;ss.forEach(d=>{if(d.data().perfect)perfect++});$('#mPerfect').textContent=perfect;$('#recentSessions').innerHTML=ss.docs.slice(0,12).map(d=>{const x=d.data();return `<div class="row"><div><b>${esc(x.displayName||'Pelaaja')}</b><div class="muted">${fmt(x.createdAt)} · ${x.score||0}/${x.targets||10} · virheitä ${x.misses||0}</div></div><span class="badge">${x.perfect?'Virheetön':'Harjoitus'}</span></div>`}).join('')||'<p>Ei harjoituksia vielä.</p>'}
async function loadPlayers(reset=false){if(reset){lastPlayerDoc=null;$('#playerList').innerHTML=''}let q=db.collection('players');const term=$('#playerSearch').value.trim().toLocaleLowerCase('fi-FI');if(term)q=q.orderBy('displayNameLower').startAt(term).endAt(term+'');else q=q.orderBy('lastPlayedAt','desc');if(lastPlayerDoc)q=q.startAfter(lastPlayerDoc);const s=await q.limit(50).get();lastPlayerDoc=s.docs.at(-1)||null;s.docs.forEach(d=>{const p={id:d.id,...d.data()};const el=document.createElement('div');el.className='row';el.innerHTML=`<div><b>${esc(p.displayName)}</b><div class="muted">Koodi ${esc(p.code)} · ${(p.cabinetIds||[]).length} palkintoa · ${fmt(p.lastPlayedAt)}</div></div><button class="secondary">Avaa</button>`;el.querySelector('button').onclick=()=>openPlayer(p);$('#playerList').appendChild(el)});$('#moreBtn').classList.toggle('hidden',s.size<50)}
$('#searchBtn').onclick=()=>loadPlayers(true);$('#reloadPlayers').onclick=()=>{$('#playerSearch').value='';loadPlayers(true)};$('#moreBtn').onclick=()=>loadPlayers(false);
async function openPlayer(p){const ss=await db.collection('players').doc(p.id).collection('sessions').orderBy('createdAt','desc').limit(30).get();const sessions=ss.docs.map(d=>d.data());$('#playerDetail').innerHTML=`<h2>${esc(p.displayName)}</h2><div class="detail"><div class="panel"><p><b>Pelikoodi:</b> ${esc(p.code)}</p><p><b>Viimeksi:</b> ${fmt(p.lastPlayedAt)}</p><p><b>Pelaaja-ID:</b><br><span class="muted">${esc(p.id)}</span></p><h3>Palkintokaappi</h3><div class="cabinet">${(p.cabinetIds||[]).map(rewardIcon).join(' ')||'Tyhjä'}</div><div class="actions"><button id="newCode" class="secondary">Vaihda koodi</button><button id="clearCab" class="secondary">Nollaa palkintokaappi</button><button id="deletePlayer" class="danger">Poista pelaaja</button></div></div><div class="panel"><h3>Viimeisimmät harjoitukset</h3><table class="table"><tr><th>Aika</th><th>Tulos</th><th>Virheet</th></tr>${sessions.map(x=>`<tr><td>${fmt(x.createdAt)}</td><td>${x.score||0}/${x.targets||10}</td><td>${x.misses||0}</td></tr>`).join('')||'<tr><td colspan="3">Ei harjoituksia</td></tr>'}</table></div></div>`;$('#playerDialog').showModal();$('#newCode').onclick=()=>changeCode(p);$('#clearCab').onclick=async()=>{if(confirm('Tyhjennetäänkö palkintokaappi?')){await updatePlayer(p,{cabinetIds:[]});p.cabinetIds=[];$('#playerDialog').close();openPlayer(p);loadPlayers(true)}};$('#deletePlayer').onclick=()=>removePlayer(p)}
let rewardCache={bear:'🧸',train:'🚂',dino:'🦖',frog:'🐸',trumpet:'🎺',star:'⭐',duck:'🦆',crown:'👑',robot:'🤖',gift:'🎁'};function rewardIcon(id){return rewardCache[id]||'🏅'}
async function updatePlayer(p,data){const now=Date.now();await db.collection('players').doc(p.id).set({...data,updatedAt:now},{merge:true});const pub={};if('cabinetIds'in data)pub.cabinetCount=data.cabinetIds.length;if(Object.keys(pub).length)await db.collection('publicPlayers').doc(p.id).set({...pub,updatedAt:now},{merge:true})}
async function changeCode(p){let code;for(let i=0;i<1000;i++){code=String(Math.floor(100+Math.random()*900));try{await db.runTransaction(async tx=>{const n=db.collection('playerCodes').doc(code),o=db.collection('playerCodes').doc(String(p.code));if((await tx.get(n)).exists)throw Error('taken');tx.set(n,{uid:p.id,createdAt:Date.now()});tx.delete(o);tx.update(db.collection('players').doc(p.id),{code,updatedAt:Date.now()})});break}catch(e){if(e.message!=='taken')throw e}}p.code=code;alert('Uusi pelikoodi: '+code);$('#playerDialog').close();openPlayer(p);loadPlayers(true)}
async function removePlayer(p){if(!confirm('Poistetaanko '+p.displayName+' pysyvästi?'))return;const b=db.batch();b.delete(db.collection('players').doc(p.id));b.delete(db.collection('publicPlayers').doc(p.id));b.delete(db.collection('playerCodes').doc(String(p.code)));await b.commit();$('#playerDialog').close();loadPlayers(true);loadOverview()}
async function loadLevels(){const s=await db.collection('gameConfig').doc('levels').collection('items').orderBy('order').get();$('#levelList').innerHTML=s.docs.map(d=>itemRow('level',d.id,d.data())).join('')||'<p>Ei tasoja vielä.</p>';wireEditButtons()}
async function loadRewards(){const s=await db.collection('gameConfig').doc('rewards').collection('items').orderBy('order').get();s.docs.forEach(d=>rewardCache[d.id]=d.data().icon||'🏅');$('#rewardList').innerHTML=s.docs.map(d=>itemRow('reward',d.id,d.data())).join('')||'<p>Ei omia palkintoasetuksia. Pelin oletuspalkinnot ovat käytössä.</p>';wireEditButtons()}
function itemRow(type,id,x){const info=type==='level'?`${esc((x.notes||[]).join(' '))} · tavoite ${x.targetTime||'–'} s · ${x.requiredPerfectRuns||0} virheetöntä`:`${esc(x.icon||'🏅')} ${esc(x.name||id)}`;return `<div class="row"><div><b>${esc(x.name||id)}</b><div class="muted">${info}</div></div><div class="actions"><button class="secondary editItem" data-type="${type}" data-id="${esc(id)}">Muokkaa</button><button class="danger deleteItem" data-type="${type}" data-id="${esc(id)}">Poista</button></div></div>`}
function wireEditButtons(){document.querySelectorAll('.editItem').forEach(b=>b.onclick=()=>editItem(b.dataset.type,b.dataset.id));document.querySelectorAll('.deleteItem').forEach(b=>b.onclick=()=>deleteItem(b.dataset.type,b.dataset.id))}
$('#addLevel').onclick=()=>editItem('level','');$('#addReward').onclick=()=>editItem('reward','');
async function editItem(type,id){let data={};if(id){const d=await db.collection('gameConfig').doc(type==='level'?'levels':'rewards').collection('items').doc(id).get();data=d.data()||{}}currentEdit={type,id};$('#editTitle').textContent=(id?'Muokkaa ':'Lisää ')+(type==='level'?'taso':'palkinto');$('#editFields').innerHTML=type==='level'?`<div class="formgrid"><label>Tunniste<input id="eId" value="${esc(id)}" ${id?'disabled':''}></label><label>Nimi<input id="eName" value="${esc(data.name||'')}"></label><label>Sävelet pilkuilla<input id="eNotes" value="${esc((data.notes||[]).join(','))}"></label><label>Järjestys<input id="eOrder" type="number" value="${data.order||1}"></label><label>Tavoiteaika sekunteina<input id="eTime" type="number" step="0.1" value="${data.targetTime||''}"></label><label>Virheettömiä avaukseen<input id="eRuns" type="number" value="${data.requiredPerfectRuns||10}"></label></div>`:`<div class="formgrid"><label>Tunniste<input id="eId" value="${esc(id)}" ${id?'disabled':''}></label><label>Nimi<input id="eName" value="${esc(data.name||'')}"></label><label>Emoji<input id="eIcon" value="${esc(data.icon||'🏅')}"></label><label>Järjestys<input id="eOrder" type="number" value="${data.order||1}"></label></div>`;$('#editDialog').showModal()}
$('#cancelEdit').onclick=()=>$('#editDialog').close();$('#saveEdit').onclick=async()=>{const id=$('#eId').value.trim();if(!id)return alert('Tunniste tarvitaan');const x={name:$('#eName').value.trim(),order:Number($('#eOrder').value)||1,updatedAt:Date.now()};if(currentEdit.type==='level'){x.notes=$('#eNotes').value.split(',').map(s=>s.trim()).filter(Boolean);x.targetTime=Number($('#eTime').value)||null;x.requiredPerfectRuns=Number($('#eRuns').value)||0}else x.icon=$('#eIcon').value.trim()||'🏅';await db.collection('gameConfig').doc(currentEdit.type==='level'?'levels':'rewards').collection('items').doc(id).set(x,{merge:true});$('#editDialog').close();currentEdit.type==='level'?loadLevels():loadRewards()}
async function deleteItem(type,id){if(!confirm('Poistetaanko tämä määritys?'))return;await db.collection('gameConfig').doc(type==='level'?'levels':'rewards').collection('items').doc(id).delete();type==='level'?loadLevels():loadRewards()}
